name: 'Code Review Action'
description: 'Runs code review'
author: 'me'

inputs:
  api-key:
    description: 'API key for the Codex service (e.g., OpenAI API key or your SaaS license key). This will be used as OPENAI_API_KEY in the container.'
    required: true
  pat-key: 
    description: 'GitHub PAT'
    required: true

runs:
  using: 'docker'
  # Replace with your actual public image path on GHCR or Docker Hub
  # Example: image: 'docker://ghcr.io/rspcunningham/codex-review-image:v1.0.0'
  image: 'docker://ghcr.io/rspcunningham/code-review-test:latest' 
  env:
    # Pass inputs to the Docker container
    INPUT_API_KEY: ${{ inputs.api-key }}

branding:
  icon: 'code'
  color: 'blue' 
