name: 'Code Review Action'
description: 'Runs code review'
author: 'me'

inputs:
  api-key:
    description: 'API key for the Codex service (e.g., OpenAI API key). This will be used as OPENAI_API_KEY in the container.'
    required: true
  pat-key:
    description: 'GitHub PAT. This will be used as INPUT_PAT_KEY in the container.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull Docker Image
      shell: bash
      run: docker pull ghcr.io/rspcunningham/code-review-test:latest
      # This command will use the Docker login session established by
      # docker/login-action in the calling workflow.

    - name: Run Code Review Container
      shell: bash
      run: |
        docker run --rm \
          -e OPENAI_API_KEY=${{ inputs.api-key }} \
          -v "${{ github.workspace }}":/github/workspace \
          -w /github/workspace \
          ghcr.io/rspcunningham/code-review-test:latest

branding:
  icon: 'code'
  color: 'blue' 
